# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "promotions-statistics-app"
client_id = "59ff7eb29a3f7784d37da3aa63d2411c"
application_url = "https://merger-dentists-merchants-rain.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://merger-dentists-merchants-rain.trycloudflare.com/auth/callback",
  "https://merger-dentists-merchants-rain.trycloudflare.com/auth/shopify/callback",
  "https://merger-dentists-merchants-rain.trycloudflare.com/api/auth/callback",
  "https://merger-dentists-merchants-rain.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abra-volo-dev.myshopify.com"
